enabled_locales: ["en"]
user:
  start_year: 1960
  max_name_size: 50
  max_email_size: 255
  min_password_size: 6
  avatar_profile: 200

cosmetic:
  cosmetic_size: 130x150
  per_page: 24

blogs:
  per_page: 10
  avatar_comment: 50
  per_page: 24

admin:
  cosmetic:
    image_size: 50
    page_index: 1
    per_page: 20
  user_table:
    size: "120x140"
  user:
    per_page: 24
cosmetics:
  show:
    sizel: 200x250
    sizes: 130x140
header:
  size: "1400x400"
